processes = []

[[buildpacks]]
  api = "0.7"
  id = "runtime/dependencies"
  version = "0.0.1"
  extension = true

[[dockerfiles]]
  extension_id = "runtime/dependencies"
  path = "/layers/runtime_dependencies/Dockerfile"
  type = "run"

[[dockerfiles]]
  extension_id = "runtime/dependencies"
  path = "/layers/runtime_dependencies/Dockerfile"
  type = "build"
